'use client';

import { buttonVariants } from "@/components/ui/button";
import { page_routes } from "@/lib/routes-config";
import { MoveUpRightIcon, TerminalIcon, ChevronRight } from "lucide-react";
import Link from "next/link";

const current_projects = [
  {
    heading: 'Single-cell Embryo Atlas',
    subheading: 'X.tropicalis embryo scRNAseq (NF 8-21)',
    url: `https://xenopus.hms.harvard.edu/Embryo.html`
  },
  {
    heading: 'Xenopus Protein Atlas',
    subheading: 'X.tropicalis adult organs bulk proteomics',
    url: `https://kirschnerlab.connect.hms.harvard.edu/proteomics/`
  },
  // {
  //   heading: '3D fly through models',
  //   subheading: 'trending memecoins today?',
  //   url: `https://kirschner.med.harvard.edu/MADX.html`
  // },
  {
    heading: 'Oocyte proteomics',
    subheading: 'X.laevis oocytes proteins and phosphoproteins',
    url: ` https://xenopus.hms.harvard.edu/index_oocyte.html`
  },
  {
    heading: 'Xenopus embryo bulk proteomics',
    subheading: '',
    url: 'https://www.xenbase.org/xenbase/geneExpression/geneExpressionSearch.do?method=display'
  },
  {
    heading: 'X.laevis protein - mRNA  comparison',
    subheading: '',
    url: `https://kirschner.med.harvard.edu/MADX.html`
  },
  {
    heading: 'X.laevis - X.tropicalis mRNA comparison',
    subheading: '',
    url: 'https://kirschner.med.harvard.edu/Xenopus_Transcriptomics.html'
  }
]

export default function Home() {
  return (
    <div className="flex sm:min-h-[91vh] min-h-[88vh] flex-col items-center justify-center text-center px-2 py-8">
      {/* <Link
        href="https://github.com/nisabmohd/Documentation-Template"
        target="_blank"
        className="mb-5 sm:text-lg flex items-center gap-2 underline underline-offset-4"
      >
        Follow along on GitHub{" "}
        <MoveUpRightIcon className="w-4 h-4 font-extrabold" />
      </Link> */}
      <h1 className="text-3xl font-bold mb-4 sm:text-7xl">
        The site is under development.
      </h1>
      <p className="mb-8 sm:text-xl max-w-[800px] text-muted-foreground">
        All the resources generated by the XenCAT project funded by NIH OD031956 will be available here.
      </p>
      <p className="mb-8 sm:text-xl max-w-[800px] text-muted-foreground">
        Meanwhile, you can browse currently available resources:
      </p>

      <Projects/>
      {/* <div className="flex flex-row items-center gap-5">
        <Link
          href={`/docs/${page_routes[0].href}`}
          className={buttonVariants({ className: "px-6", size: "lg" })}
        >
          Get Stared
        </Link>
        <Link
          href="#"
          className={buttonVariants({
            variant: "outline",
            className: "px-6",
            size: "lg",
          })}
        >
          Customize
        </Link>
      </div> */}
      {/* <span className="flex flex-row items-center gap-2 text-zinc-400 text-md mt-7 -mb-12 max-[800px]:mb-12">
        <TerminalIcon className="w-4 h-4 mr-1" /> ~ npx this-library-name@latest
      </span> */}
    </div>
  );
}

const redirect = (url: string) => {
  window.location.href = url;
};

function Projects() {
  return (
    <div className="mx-auto sm:max-w-2xl sm:px-4">
      <div className="mb-4 grid grid-cols-1 gap-2 px-4 sm:px-0">
        {current_projects.map((project) =>
          <Link
              href={project.url}
              key={project.heading}
              className="cursor-pointer rounded-lg border bg-white p-4 hover:bg-zinc-50 dark:bg-zinc-950 dark:hover:bg-zinc-900 flex justify-between items-center"
              // onClick={async () => {
              //   setMessages(currentMessages => [
              //     ...currentMessages,
              //     {
              //       id: nanoid(),
              //       display: <UserMessage>{example.message}</UserMessage>
              //     }
              //   ])

              //   const responseMessage = await submitUserMessage(
              //     example.message
              //   )

              //   setMessages(currentMessages => [
              //     ...currentMessages,
              //     responseMessage
              //   ])
              // }}
              onClick={() => redirect(project.url)}
              >
              <div className="col-11">
                <div className="text-sm font-semibold">{project.heading}</div>
                <div className="text-sm text-zinc-600">
                  {project.subheading}
                </div>
              </div>
              <div className="col-1">
                <ChevronRight />
              </div>
            </Link>)}
      </div>
    </div>
  );
}